version: '3.8'

services:

  axon-server:
    image: axoniq/axonserver:4.5.1
    container_name: axon-server
    restart: unless-stopped
    ports:
      - "8024:8024"
      - "8124:8124"

  mysql:
    image: mysql:8.0.24
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=customerdb
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 30s

  postgres:
    container_name: postgres
    image: postgres:13.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=restaurantdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U postgres"
      start_period: 30s

  mongodb:
    image: mongo:4.4.5
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: "echo 'db.stats().ok' | mongo localhost:27017/foodorderingdb --quiet"
      start_period: 30s
