services:

  axon-server:
    image: 'axoniq/axonserver:4.6.11'
    container_name: 'axon-server'
    restart: 'unless-stopped'
    ports:
      - '8024:8024'
      - '8124:8124'

  mysql:
    image: 'mysql:9.6.0'
    container_name: 'mysql'
    restart: 'unless-stopped'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_DATABASE=customerdb'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 3s
      timeout: 3s
      retries: 5

  postgres:
    container_name: 'postgres'
    image: 'postgres:18.3'
    restart: 'unless-stopped'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=restaurantdb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  mongodb:
    image: 'mongo:8.2.5'
    container_name: 'mongodb'
    restart: 'unless-stopped'
    ports:
      - '27017:27017'
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongosh localhost:27017/foodorderingdb --quiet"]
      interval: 3s
      timeout: 3s
      retries: 5
